# Generated by Django 4.2.13 on 2024-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='temperature',
            field=models.IntegerField(default=30),
        ),
    ]
